apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  labels:
    app: database-depl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database-container
        image: mysql:5.7
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d

      volumes:               
      - name: initdb
        configMap:
          name: mysql-initdb    

