apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  labels:
    app: database-depl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database-container
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 80
